### ISSUE TITLE
Select componets

### ISSUE THREAD

**Issue by jake-g00dwin** [jake-g00dwin/PersonalDataAcquisitionPrototype#15]
- [x] Select 1/2 Micro-controllers (Makes project resistant to chip shortages)
- [x] Select the SBC(single board computer) or Main controller
- [x] Create git repo for micro-controller 1
- [ ] Create git repo for micro-controller 2
- [x] Create git repo for SBC
- [x] Create repo for the schematics

**Comment by jake-g00dwin** [comment]
Meeting to work on role selection and hardware at 11 2023-11-08

**Comment by jake-g00dwin** [comment]
Have shared document created with the options and prices listed. Some key areas brought up and researched are:

- Bread-boarding is cheaper than Mikroe bus official parts.
- duplicate components mean more work in parallel & redundancy in case of component failure.
- dupont pins can be used/soldered on final prototype(means we could avoid custom PCBs if desired)
- The SBC should focus on I/O and R/W endurance.

Component selection will be finalized at next team meeting on 2023-11-09

REPO doc: [link](https://github.com/Personal-Data-Acquisition/PDA_paperwork/tree/main/hardware)
gdrive link: [link](https://docs.google.com/document/d/1hG17OLzUmapjAF-JAW2NogMZkPDOjmAY-gwm8BZJcFg/edit?pli=1)

**Comment by crispyDyne** [comment]
I agree that Mikroe will be more expensive, but seems worth it if it saves time & troubleshooting. I'm willing to pay for one or two complete sets of whatever we decide on (within reason).

Here are my default thoughts for hardware. Certainly open to discussion
- For the primary logger: Raspberry Pi. I get the felling it will be plenty powerful for handling CAN communication. 
- CAN communication on Pi [CAN Hat]([amazon](https://www.amazon.com/RS485-CAN-HAT-Long-Distance-Communication/dp/B07VMB1ZKH), [direct](https://www.waveshare.com/rs485-can-hat.htm))
- Micro Controller - The two below should be relatively easy to switch between
  - [STM32F413RHTx](https://www.mikroe.com/mcu-card-29-for-stm32-stm32f413rh) Should be overkill for basic functionality and includes CAN.
  - [STM32F042C6](https://www.mikroe.com/mcu-card-6-for-stm32-stm32f042c6) Lower end & cheaper. Should still be fine? Also includes CAN.
- For prototyping [Uni-Clicker](https://www.mikroe.com/uni-clicker)
- Programmers: ST-Link/V2
    - [Amazon Knock-Off](https://www.amazon.com/s?k=st+link+v2) (this is what I use)
    - [Official hardware from STM](https://www.st.com/en/development-tools/st-link-v2.html)
- Sensors (we don't need to do all of them)
  - GPS [MEO-M9N](https://www.mikroe.com/gnss-7-click) <-- Would be really cool. Could incorporate 9-dof and work on sensor fusion?
  - Analog to digital converter
    - [ADC 4 Click](https://www.mikroe.com/adc-4-click) : This will be easier to prototype since it comes on a click board.
    - [AD7124-8](https://www.digikey.com/en/products/detail/analog-devices-inc/EVAL-AD7124-8-PMDZ/13152102): This one is a bit better.
  - Accelerometer / Gyro / Magnetometer [BMX055](https://www.mikroe.com/9dof-3-click)
