### ISSUE TITLE
Create a set of git repos/submodules for the Main project.

### ISSUE THREAD

**Issue by jake-g00dwin** [jake-g00dwin/PersonalDataAcquisitionPrototype#3]
We should probably look into creating submodules/repos for each of the sensor+micro-controller modules that we plan to use in the main project.

**Comment by goodwjak** [comment]
In progress, have created two separate repos for two possible micro-controllers

**Comment by jake-g00dwin** [comment]
Done, Have created at least one of every needed type of sub-module repo.
